version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 0o9i*U&Y

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443

    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - /root/dockerfiles/appsConfigs/nginx/hosts:/etc/nginx/conf.d
      - /root/dockerfiles/appsConfigs/nginx/www:/var/www
      - /root/dockerfiles/appsConfigs/nginx/logs:/var/logs

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - /root/dockerfiles/appsConfigs/redis/data:/data

  # gitlab:
  #   image: 'gitlab/gitlab-ce:latest'
  #   container_name: gitlab
  #   restart: always
  #   hostname: 'gitlab.cbsky.ru'
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'https://cbsky.ru:8929'
  #       gitlab_rails['gitlab_shell_ssh_port'] = 2224
  #   ports:
  #     - '8929:8929'
  #     - '2224:22'
  #     - '4443:443'
  #   volumes:
  #     - '/root/dockerfiles/appsConfigs/gitlab/config:/etc/gitlab'
  #     - '/root/dockerfiles/appsConfigs/gitlab/logs:/var/log/gitlab'
  #     - '/root/dockerfiles/appsConfigs/gitlab/data:/var/opt/gitlab'
  #   shm_size: '256m'

  # gitlab-runner:
  #   container_name: gitlab-runner
  #   image: gitlab/gitlab-runner:latest
  #   restart: always
  #   volumes:
  #     - '/root/dockerfiles/appsConfigs/gitlabRunner/data:/home/gitlab_ci_multi_runner/data'
  #     - '/root/dockerfiles/appsConfigs/gitlabRunner/config:/etc/gitlab-runner'
  #     - '/var/run/docker.sock:/var/run/docker.sock:rw'
  #   environment:
  #     - CI_SERVER_URL=https://cbsky.ru/ci

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /root/dockerfiles/appsConfigs/rabbitmq/data:/var/lib/rabbitmq
      - /root/dockerfiles/appsConfigs/rabbitmq/logs:/var/log/rabbitmq

  portainer:
    #web gui для управления контейнерами
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/dockerfiles/appsConfigs/portainer/data:/data
    ports:
      - 9000:9000

  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - 33000:3000
      - 33001:3001
    shm_size: "1gb"
    restart: unless-stopped

  netdata:
    image: netdata/netdata
    container_name: netdata
    pid: host
    network_mode: host
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    ports:
      - 19999:19999
    volumes:
      - /root/dockerfiles/appsConfigs/netdata/config:/etc/netdata
      - /root/dockerfiles/appsConfigs/netdata/data:/var/lib/netdata
      - /root/dockerfiles/appsConfigs/netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
