version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 0o9i*U&Y

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443

    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - /root/dockerfiles/appsConfigs/nginx/hosts:/etc/nginx/conf.d
      - /root/dockerfiles/appsConfigs/nginx/www:/var/www
      - /root/dockerfiles/appsConfigs/nginx/logs:/var/logs

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - /root/dockerfiles/appsConfigs/redis/data:/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /root/dockerfiles/appsConfigs/rabbitmq/data:/var/lib/rabbitmq
      - /root/dockerfiles/appsConfigs/rabbitmq/logs:/var/log/rabbitmq

  portainer:
    #web gui для управления контейнерами
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/dockerfiles/appsConfigs/portainer/data:/data
    ports:
      - 9000:9000
