name: Deployment web api chainlink

concurrency: production

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build frontend docker image
        uses: docker/build-push-action@v5
        with:
          context: ./usefulApps/services/ts/webApiForChainlink/web-api-chainlink
          file: ./usefulApps/services/ts/webApiForChainlink/web-api-chainlink/Dockerfile
          push: false
          tags: web-api-for-chainlink:latest
          outputs: type=local,dest=web-api-for-chainlink.tar
      - name: install sshpass
        run: sudo apt-get install sshpass
      - name: try to push
        run: sshpass -p zDnNgX0c scp -r ./web-api-for-chainlink.tar githubcd@94.26.248.117/./dockerImages
