name: Dotnet builds and tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-dbCreatorAndMigrator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "Columbiysky/usefulServices"

      - name: Set up dontet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
                
      - name: Install dependencies
        working-directory: usefulApps/tools/DbCreatorAndMigrator
        run: dotnet restore
      
      - name: Build
        working-directory: usefulApps/tools/DbCreatorAndMigrator
        run: dotnet build
