name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build dbTool
        working-directory: usefulApps/tools/dbTool
        run: go build -v .

      - name: Build sso
        working-directory: usefulApps/sso
        run: go build -v .

      - name: Build backend
        working-directory: usefulApps/backend/src
        run: go build -v .

      - name: Test sso
        working-directory: usefulApps/sso/tests
        run: go test -v .

      - name: Build backend docker image
        uses: docker/build-push-action@v5
        with:
          context: ./usefulApps/backend/src
          file: ./Dockerfile
          push: false
          tags: backend:latest
