name: Go builds and tests

on:
  push:
    branches: ["main"]
    paths: 
      - './goBackendBuildAndTest.yml'
      - 'usefulApps/backend/**'
      - 'usefulApps/sso/**'
  pull_request:
    branches: ["main"]
    paths: 
      - './goBackendBuildAndTest.yml'
      - 'usefulApps/backend/**'
      - 'usefulApps/sso/**'

jobs:
  build-sso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "Columbiysky/usefulServices"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build sso
        working-directory: usefulApps/sso
        run: go build -v .

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "Columbiysky/usefulServices"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build backend
        working-directory: usefulApps/backend/src
        run: go build -v .

  # test-sso:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: "1.21"

  #     - name: Test sso
  #       working-directory: usefulApps/sso/tests
  #       run: go test -v .
