name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build dbTool
        working-directory: usefulApps/tools/dbTool
        run: go build -v .

      - name: Build sso
        working-directory: usefulApps/sso
        run: go build -v .

      - name: Build backend
        working-directory: usefulApps/backend/src
        run: go build -v .

    # - name: Test
    #   run: go test -v ./...
