name: Go DOCKER build

on:
  workflow_run:
    workflows: ["Go builds and tests"]
    types: [completed]

jobs:
  build-backend-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build backend docker image
        uses: docker/build-push-action@v6
        with:
          context: ./usefulApps/backend/src
          file: ./usefulApps/backend/src/Dockerfile
          push: false
          tags: backend:latest

  build-sso-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build sso docker image
        uses: docker/build-push-action@v6
        with:
          context: ./usefulApps/sso
          file: ./usefulApps/sso/Dockerfile
          push: false
          tags: sso:latest
