name: Go DOCKER build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build backend docker image
        uses: docker/build-push-action@v5
        with:
          context: ./usefulApps/backend/src
          file: ./usefulApps/backend/src/Dockerfile
          push: false
          tags: backend:latest

      - name: Build sso docker image
        uses: docker/build-push-action@v5
        with:
          context: ./usefulApps/sso
          file: ./usefulApps/sso/Dockerfile
          push: false
          tags: sso:latest
