name: Go DOCKER build

on:
  push:
    branches: ["main"]
    paths: 
      - './goDockerBuilds.yml'
      - 'usefulApps/backend/**'
      - 'usefulApps/sso/**'
  pull_request:
    branches: ["main"]
    paths: 
      - './goDockerBuilds.yml'
      - 'usefulApps/backend/**'
      - 'usefulApps/sso/**'

jobs:
  build-backend-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build backend docker image
        uses: docker/build-push-action@v5
        with:
          context: ./usefulApps/backend/src
          file: ./usefulApps/backend/src/Dockerfile
          push: false
          tags: backend:latest
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

  build-sso-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build sso docker image
        uses: docker/build-push-action@v5
        with:
          context: ./usefulApps/sso
          file: ./usefulApps/sso/Dockerfile
          push: false
          tags: sso:latest
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
