name: Integration Test
on:
  push:
jobs:
  integration:
    services:
      postgres10:
        image: postgres:latest
        env:
          POSTGRES_DB: integration
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "Columbiysky/usefulServices"

      - name: Set up dontet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
                
      - name: Install dependencies
        working-directory: usefulApps/tools/DbCreatorAndMigrator
        run: dotnet restore
      
      - name: Build
        working-directory: usefulApps/tools/DbCreatorAndMigrator
        run: dotnet build

      - name: Run creator and migrator
        run: |
            ls