name: Node.js DOCKER build

on:
  workflow_run:
    workflows: ["Node.js build and test"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build frontend docker image
        uses: docker/build-push-action@v6
        with:
          context: ./usefulApps/frontend
          file: ./usefulApps/frontend/Dockerfile
          push: false
          tags: frontend:latest
