name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        working-directory: usefulApps/frontend
        run: npm ci
      - name: Build
        working-directory: usefulApps/frontend
        run: npm run build
      # - name: Test
      #   working-directory: usefulApps/frontend
      #   run: npm test

      - name: Build frontend docker image
        uses: docker/build-push-action@v5
        with:
          context: ./usefulApps/frontend
          file: ./usefulApps/frontend/Dockerfile
          push: false
          tags: frontend:latest
