name: Node.js build and test

on:
  push:
    branches: ["main"]
    paths: 
      - './jsFrontendBuildAndTest.yml'
      - 'usefulApps/frontend/**'
  pull_request:
    branches: ["main"]
    paths: 
      - './jsFrontendBuildAndTest.yml'
      - 'usefulApps/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "Columbiysky/usefulServices"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install dependencies
        working-directory: usefulApps/frontend
        run: npm ci
      - name: Build
        working-directory: usefulApps/frontend
        run: npm run build
