name: Nest.js DOCKER build

on:
  push:
    branches: ["main"]
    paths: 
      - './nestJsDockerBuild.yml'
      - 'usefulApps/services/ts/webApiForChainlink/**'
  pull_request:
    branches: ["main"]
    paths: 
      - './nestJsDockerBuild.yml'
      - 'usefulApps/services/ts/webApiForChainlink/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build frontend docker image
        uses: docker/build-push-action@v5
        with:
          context: ./usefulApps/services/ts/webApiForChainlink
          file: ./usefulApps/services/ts/webApiForChainlink/Dockerfile
          push: false
          tags: webApiForChainlink:latest
