name: Nest.js DOCKER build

on:
  push:
    branches: ["main"]
    paths: 
      - './nestJsDockerBuild.yml'
      - 'usefulApps/services/ts/**'
  pull_request:
    branches: ["main"]
    paths: 
      - './nestJsDockerBuild.yml'
      - 'usefulApps/services/ts/**'
  workflow_run:
    workflows: ["Nest.js build and test"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build frontend docker image
        uses: docker/build-push-action@v6
        with:
          context: ./usefulApps/services/ts/web-api-chainlink
          file: ./usefulApps/services/ts/web-api-chainlink/Dockerfile
          push: false
          tags: web-api-for-chainlink:latest
