name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install dependencies
        working-directory: usefulApps/executors/python
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Test 'app' module
        working-directory: usefulApps/executors/python
        run: python test_main.py -v