name: Python test

on:
  push:
    branches: ["main"]
    paths: 
      - "./pythonExecutorsTests.yml"
      - "../../usefulApps/executors/python/**"
  pull_request:
    branches: ["main"]
    paths: 
      - "./pythonExecutorsTests.yml"
      - "../../usefulApps/executors/python/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: "Columbiysky/usefulServices"
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"
      - name: Install dependencies
        working-directory: usefulApps/executors/python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test 'app' module
        working-directory: usefulApps/executors/python
        run: python test_main.py -v
